DefaultContentLanguage = "en"
baseURL = "http://example.org/"
copyright = "This is a customized copyright."
languageCode = "en-us"
theme = "diary"
title = "A Hugo Site"
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "perldoc"
tabWidth = 4
[[menu.main]]
name = "RSS Feed"
url = "/index.xml"
weight = 4
[[menu.main]]
name = "Archive"
url = "/posts"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2
[params]
description = "My HomePage Description"
enableGitalk = true
enableOpenGraph = true
enableTwitterCards = true
subtitle = "Themed by Diary."
title = "My Blog"
[params.gitalk]
client_id = "your client id"
client_secret = "your client secret"
owner = "user"
repo = "repo name"
[taxonomies]
category = "categories"
tag = "tags"
